### ISSUE TITLE
Fix broken links in the "Formal Confluence for φ-Calculus in Lean 4" paper

### ISSUE THREAD

**Issue by deemp** [objectionary/proof#49]
## Problem

Currently, the paper contains broken links. Examples:
- https://www.objectionary.com/proof/docs/Minimal/ARS.html#ReflTransGen.trans
- https://www.objectionary.com/proof/docs/Minimal/Calculus.html#Minimal/Calculus

**Comment by Anatolay** [comment]
Closed in #49

**Comment by 0crat** [comment]
@deemp Hey there! 👋 Thanks for submitting the ticket, even though it wasn't accepted this time. As per our policy, there's a -16 point deduction, but don't let that discourage you! Your current balance is still [+41](https://www.eolang.org/zerocracy/objectionary-vitals.html), which is great. Keep [reporting](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) those bugs and suggesting improvements – it's crucial for our project's quality. Just be a bit more careful next time, and remember, [bugs are always welcome](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html)!

**Comment by deemp** [comment]
Actually closed in #50
